# Generated by Django 5.2.10 on 2026-02-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='dashboard/images/snapshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gold_summary', models.TextField(blank=True)),
                ('silver_summary', models.TextField(blank=True)),
                ('oil_summary', models.TextField(blank=True)),
            ],
        ),
    ]
